"""add parent_id to comment

Revision ID: 34175636af81
Revises: d7e28572c900
Create Date: 2026-03-05 17:19:59.516969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34175636af81'
down_revision = 'd7e28572c900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_comment_parent',
            'comment',
            ['parent_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
