"""add video field to Post

Revision ID: 372abd1f52d3
Revises: 6b2c0655f3e1
Create Date: 2025-10-28 15:26:09.450041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372abd1f52d3'
down_revision = '6b2c0655f3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('video')

    # ### end Alembic commands ###
